#!/bin/bash

# Get the new package version
VERSION=$(node -pe "require('./package.json').version")

# Update the add-in with the latest version
scripts/update-addin-version
git add finboxio.install.xlam
cat .git/index.lock

# Update changelog
git changelog -t $VERSION
sleep 0.5
git add History.md package.json package-lock.json
