#!/bin/bash

set -e

head="${1:-HEAD}"

previous_tag=$(hub release --include-drafts | head -n 1)

if [ -z "$previous_tag" ]; then
  echo "Couldn't detect previous release tag" >&2
  exit 1
fi

git log --no-merges \
  --format='%s%n%w(0,2,2)%+b' \
  --reverse "${previous_tag}..${head}" | \
  # trim release messages
  grep -Ev "^[0-9]+\.[0-9]+\.[0-9]+[^ ]*$" | \
  # squeeze multiple newlines
  cat -s | \
  # capitalize each commit msg
  sed 's/^\(.\)/\U\1/' | \
  # add * to each commit msg
  sed -e '1~2s/^/* /'
